version: "3.4"
services:
  storjscan:
    image: img.dev.storj.io/storjup/storjscan:20220802-2
    command:
      - /app/storjscan
      - run
      - --database=postgres://storjscan@db/storjscandb
      - --tokens.endpoint=http://geth:8545
      - --tokens.contract=0x1E119A589270646585b044db12098B1e456a88Af
      - --token-price.interval=1m
      - --token-price.coinmarketcap-config.base-url=https://sandbox-api.coinmarketcap.com
      - --token-price.coinmarketcap-config.api-key=b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c
      - --token-price.coinmarketcap-config.timeout=1m
      - --api.address=0.0.0.0:12000
      - --api.keys=eu1:eu1secret,us1:us1secret
    ports:
      - "12000:12000"
    networks:
      default: null
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: storjscan
      POSTGRES_DB: storjscandb
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5442:5432"
  geth:
    image: ethereum/client-go
    command:
      - --keystore=/test-blockchain
      - --password=/test-blockchain/pass
      - --http
      - --ws
      - --dev
      - --miner.etherbase=0x158D2c25bA6107B622F288663F50f53601ab6710
      - --http.api=eth,net,web3,txpool,admin,debug
      - --ws.api=eth,net,web3,txpool,admin,debug
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --ws.addr=0.0.0.0
      - --http.corsdomain
      - "*"
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ./test-blockchain:/test-blockchain