version: "3.4"
services:
  cockroach:
    command:
    - start-single-node
    - --insecure
    - --http-addr
    - 127.0.0.1:1234
    image: cockroachdb/cockroach
    networks:
      default: null
    ports:
    - mode: ingress
      target: 26257
      published: 26257
      protocol: tcp
  geth:
    command:
    - --keystore=/test-blockchain
    - --password=/test-blockchain/pass
    - --http
    - --ws
    - --dev
    - --miner.etherbase=0x158D2c25bA6107B622F288663F50f53601ab6710
    - --http.api=eth,net,web3,txpool,admin,debug
    - --ws.api=eth,net,web3,txpool,admin,debug
    - --http.vhosts=*
    - --http.addr=0.0.0.0
    - --ws.addr=0.0.0.0
    - --http.corsdomain
    - "*"
    image: ethereum/client-go
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8545
      published: 8545
      protocol: tcp
    - mode: ingress
      target: 8546
      published: 8546
      protocol: tcp
    volumes:
    - type: bind
      source: ./test-blockchain
      target: /test-blockchain
      bind:
        create_host_path: true
  storjscan:
    command:
    - storjscan
    - run
    - --database=cockroach://root@cockroach:26257/master?sslmode=disable
    - --tokens.endpoint=http://geth:8545
    - --tokens.contract=0x1E119A589270646585b044db12098B1e456a88Af
    - --token-price.interval=1m
    - --token-price.coinmarketcap-config.base-url=https://sandbox-api.coinmarketcap.com
    - --token-price.coinmarketcap-config.api-key=b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c
    - --token-price.coinmarketcap-config.timeout=1m
    - --api.address=0.0.0.0:12000
    - --api.keys=eu1:eu1secret,us1:us1secret
    image: img.dev.storj.io/storjup/storjscan:20220830-1
    networks:
      default: null
    ports:
    - mode: ingress
      target: 12000
      published: 12000
      protocol: tcp
