-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE block_headers (
	hash bytea NOT NULL,
	number bigint NOT NULL,
	timestamp timestamp with time zone NOT NULL,
	created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( hash )
);
CREATE TABLE token_prices (
	interval_start timestamp with time zone NOT NULL,
	price bigint NOT NULL,
	PRIMARY KEY ( interval_start )
);
CREATE TABLE wallets (
	address bytea NOT NULL,
	claimed timestamp with time zone,
	satellite text NOT NULL,
	info text,
	created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( address )
);
CREATE INDEX wallets_satellite_index ON wallets ( satellite ) ;
