//lint:file-ignore U1000,ST1012 generated file
// AUTOGENERATED BY storj.io/dbx
// DO NOT EDIT.

package dbx

import (
	"bytes"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode"

	"github.com/jackc/pgx/v5/pgconn"
	_ "github.com/jackc/pgx/v5/stdlib"

	"storj.io/storj/shared/tagsql"
)

// Prevent conditional imports from causing build failures.
var _ = strconv.Itoa
var _ = strings.LastIndex
var _ = fmt.Sprint
var _ sync.Mutex

var (
	WrapErr     = func(err *Error) error { return err }
	Logger      func(format string, args ...any)
	ShouldRetry func(driver string, err error) bool

	errTooManyRows       = errors.New("too many rows")
	errUnsupportedDriver = errors.New("unsupported driver")
	errEmptyUpdate       = errors.New("empty update")
)

func logError(format string, args ...any) {
	if Logger != nil {
		Logger(format, args...)
	}
}

type ErrorCode int

const (
	ErrorCode_Unknown ErrorCode = iota
	ErrorCode_UnsupportedDriver
	ErrorCode_NoRows
	ErrorCode_TxDone
	ErrorCode_TooManyRows
	ErrorCode_ConstraintViolation
	ErrorCode_EmptyUpdate
)

type Error struct {
	Err         error
	Code        ErrorCode
	Driver      string
	Constraint  string
	QuerySuffix string
}

func (e *Error) Error() string {
	return e.Err.Error()
}

func (e *Error) Unwrap() error {
	return e.Err
}

func wrapErr(e *Error) error {
	if WrapErr == nil {
		return e
	}
	return WrapErr(e)
}

func makeErr(err error) error {
	if err == nil {
		return nil
	}
	var e *Error
	if errors.As(err, &e) {
		return wrapErr(e)
	}
	e = &Error{Err: err}
	switch {
	case errors.Is(err, sql.ErrNoRows):
		e.Code = ErrorCode_NoRows
	case errors.Is(err, sql.ErrTxDone):
		e.Code = ErrorCode_TxDone
	}
	return wrapErr(e)
}

func shouldRetry(driver string, err error) bool {
	if ShouldRetry == nil {
		return false
	}
	return ShouldRetry(driver, err)
}

func unsupportedDriver(driver string) error {
	return wrapErr(&Error{
		Err:    errUnsupportedDriver,
		Code:   ErrorCode_UnsupportedDriver,
		Driver: driver,
	})
}

func emptyUpdate() error {
	return wrapErr(&Error{
		Err:  errEmptyUpdate,
		Code: ErrorCode_EmptyUpdate,
	})
}

func tooManyRows(query_suffix string) error {
	return wrapErr(&Error{
		Err:         errTooManyRows,
		Code:        ErrorCode_TooManyRows,
		QuerySuffix: query_suffix,
	})
}

func constraintViolation(err error, constraint string) error {
	return wrapErr(&Error{
		Err:        err,
		Code:       ErrorCode_ConstraintViolation,
		Constraint: constraint,
	})
}

func closeRows(rows tagsql.Rows, err *error) {
	rowsErr := rows.Err()
	closeErr := rows.Close()
	if *err != nil {
		// throw away errors from .Err() and .Close(), if any; they are almost certainly less important
		// than the error we already have
		return
	}
	if rowsErr != nil {
		// throw away error from .Close(), if any; it is probably less important
		*err = rowsErr
		return
	}
	*err = closeErr
}

type driver interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (tagsql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

type DB struct {
	tagsql.DB
	dbMethods

	Hooks struct {
		Now func() time.Time
	}

	driver string
}

func Open(driver, source string) (db *DB, err error) {
	var sql_db *sql.DB
	switch driver {
	case "pgx":
		sql_db, err = openpgx(source)
	case "pgxcockroach":
		sql_db, err = openpgxcockroach(source)
	default:
		return nil, unsupportedDriver(driver)
	}
	if err != nil {
		return nil, makeErr(err)
	}
	defer func(sql_db *sql.DB) {
		if err != nil {
			_ = sql_db.Close()
		}
	}(sql_db)

	if err := sql_db.Ping(); err != nil {
		return nil, makeErr(err)
	}

	db = &DB{
		DB: tagsql.Wrap(sql_db),

		driver: driver,
	}
	db.Hooks.Now = time.Now

	switch driver {
	case "pgx":
		db.dbMethods = newpgx(db)
	case "pgxcockroach":
		db.dbMethods = newpgxcockroach(db)
	default:
		return nil, unsupportedDriver(driver)
	}

	return db, nil
}

func (obj *DB) Close() (err error) {
	return obj.makeErr(obj.DB.Close())
}

func (obj *DB) Open(ctx context.Context) (*Tx, error) {
	tx, err := obj.DB.BeginTx(ctx, nil)
	if err != nil {
		return nil, obj.makeErr(err)
	}

	return &Tx{
		Tx:        tx,
		txMethods: obj.wrapTx(tx),
	}, nil
}

func DeleteAll(ctx context.Context, db *DB) (int64, error) {
	tx, err := db.Open(ctx)
	if err != nil {
		return 0, err
	}
	defer func() {
		if err == nil {
			err = db.makeErr(tx.Commit())
			return
		}

		if err_rollback := tx.Rollback(); err_rollback != nil {
			logError("delete-all: rollback failed: %v", db.makeErr(err_rollback))
		}
	}()
	return tx.deleteAll(ctx)
}

type Tx struct {
	Tx tagsql.Tx
	txMethods
}

func (tx *Tx) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	return tx.Tx.ExecContext(ctx, query, args...)
}
func (tx *Tx) QueryContext(ctx context.Context, query string, args ...any) (tagsql.Rows, error) {
	return tx.Tx.QueryContext(ctx, query, args...)
}
func (tx *Tx) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	return tx.Tx.QueryRowContext(ctx, query, args...)
}

type dialectTx struct {
	tx tagsql.Tx
}

func (tx *dialectTx) Commit() (err error) {
	return makeErr(tx.tx.Commit())
}

func (tx *dialectTx) Rollback() (err error) {
	return makeErr(tx.tx.Rollback())
}

type pgxImpl struct {
	db      *DB
	dialect __sqlbundle_pgx
	driver  driver
	txn     bool
}

func (obj *pgxImpl) Rebind(s string) string {
	return obj.dialect.Rebind(s)
}

func (obj *pgxImpl) logStmt(stmt string, args ...any) {
	pgxLogStmt(stmt, args...)
}

func (obj *pgxImpl) makeErr(err error) error {
	constraint, ok := obj.isConstraintError(err)
	if ok {
		return constraintViolation(err, constraint)
	}
	return makeErr(err)
}

func (obj *pgxImpl) shouldRetry(err error) bool {
	return !obj.txn && shouldRetry(obj.db.driver, err)
}

type pgxImpl_retryingRow struct {
	obj   *pgxImpl
	ctx   context.Context
	query string
	args  []any
}

func (obj *pgxImpl) queryRowContext(ctx context.Context, query string, args ...any) *pgxImpl_retryingRow {
	return &pgxImpl_retryingRow{
		obj:   obj,
		ctx:   ctx,
		query: query,
		args:  args,
	}
}

func (rows *pgxImpl_retryingRow) Scan(dest ...any) error {
	for {
		err := rows.obj.driver.QueryRowContext(rows.ctx, rows.query, rows.args...).Scan(dest...)
		if err != nil {
			if rows.obj.shouldRetry(err) {
				continue
			}
			// caller will wrap this error
			return err
		}
		return nil
	}
}

type pgxDB struct {
	db *DB
	*pgxImpl
}

func newpgx(db *DB) *pgxDB {
	return &pgxDB{
		db: db,
		pgxImpl: &pgxImpl{
			db:     db,
			driver: db.DB,
		},
	}
}

func (obj *pgxDB) Schema() []string {
	return []string{

		`CREATE TABLE block_headers (
	chain_id bigint NOT NULL,
	hash bytea NOT NULL,
	number bigint NOT NULL,
	timestamp timestamp with time zone NOT NULL,
	created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( chain_id, hash )
)`,

		`CREATE TABLE token_prices (
	interval_start timestamp with time zone NOT NULL,
	price bigint NOT NULL,
	PRIMARY KEY ( interval_start )
)`,

		`CREATE TABLE wallets (
	id bigserial NOT NULL,
	address bytea NOT NULL,
	claimed timestamp with time zone,
	satellite text NOT NULL,
	info text,
	created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( id )
)`,

		`CREATE INDEX wallets_satellite_index ON wallets ( satellite )`,

		`CREATE UNIQUE INDEX wallets_address_unique_index ON wallets ( address )`,
	}
}

func (obj *pgxDB) DropSchema() []string {
	return []string{

		`DROP TABLE IF EXISTS wallets`,

		`DROP TABLE IF EXISTS token_prices`,

		`DROP TABLE IF EXISTS block_headers`,
	}
}

func (obj *pgxDB) wrapTx(tx tagsql.Tx) txMethods {
	return &pgxTx{
		dialectTx: dialectTx{tx: tx},
		pgxImpl: &pgxImpl{
			db:     obj.db,
			driver: tx,
			txn:    true,
		},
	}
}

type pgxTx struct {
	dialectTx
	*pgxImpl
}

func pgxLogStmt(stmt string, args ...any) {
	// TODO: render placeholders
	if Logger != nil {
		out := fmt.Sprintf("stmt: %s\nargs: %v\n", stmt, pretty(args))
		Logger(out)
	}
}

type pgxcockroachImpl struct {
	db      *DB
	dialect __sqlbundle_pgxcockroach
	driver  driver
	txn     bool
}

func (obj *pgxcockroachImpl) Rebind(s string) string {
	return obj.dialect.Rebind(s)
}

func (obj *pgxcockroachImpl) logStmt(stmt string, args ...any) {
	pgxcockroachLogStmt(stmt, args...)
}

func (obj *pgxcockroachImpl) makeErr(err error) error {
	constraint, ok := obj.isConstraintError(err)
	if ok {
		return constraintViolation(err, constraint)
	}
	return makeErr(err)
}

func (obj *pgxcockroachImpl) shouldRetry(err error) bool {
	return !obj.txn && shouldRetry(obj.db.driver, err)
}

type pgxcockroachImpl_retryingRow struct {
	obj   *pgxcockroachImpl
	ctx   context.Context
	query string
	args  []any
}

func (obj *pgxcockroachImpl) queryRowContext(ctx context.Context, query string, args ...any) *pgxcockroachImpl_retryingRow {
	return &pgxcockroachImpl_retryingRow{
		obj:   obj,
		ctx:   ctx,
		query: query,
		args:  args,
	}
}

func (rows *pgxcockroachImpl_retryingRow) Scan(dest ...any) error {
	for {
		err := rows.obj.driver.QueryRowContext(rows.ctx, rows.query, rows.args...).Scan(dest...)
		if err != nil {
			if rows.obj.shouldRetry(err) {
				continue
			}
			// caller will wrap this error
			return err
		}
		return nil
	}
}

type pgxcockroachDB struct {
	db *DB
	*pgxcockroachImpl
}

func newpgxcockroach(db *DB) *pgxcockroachDB {
	return &pgxcockroachDB{
		db: db,
		pgxcockroachImpl: &pgxcockroachImpl{
			db:     db,
			driver: db.DB,
		},
	}
}

func (obj *pgxcockroachDB) Schema() []string {
	return []string{

		`CREATE TABLE block_headers (
	chain_id bigint NOT NULL,
	hash bytea NOT NULL,
	number bigint NOT NULL,
	timestamp timestamp with time zone NOT NULL,
	created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( chain_id, hash )
)`,

		`CREATE TABLE token_prices (
	interval_start timestamp with time zone NOT NULL,
	price bigint NOT NULL,
	PRIMARY KEY ( interval_start )
)`,

		`CREATE TABLE wallets (
	id bigserial NOT NULL,
	address bytea NOT NULL,
	claimed timestamp with time zone,
	satellite text NOT NULL,
	info text,
	created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( id )
)`,

		`CREATE INDEX wallets_satellite_index ON wallets ( satellite )`,

		`CREATE UNIQUE INDEX wallets_address_unique_index ON wallets ( address )`,
	}
}

func (obj *pgxcockroachDB) DropSchema() []string {
	return []string{

		`DROP TABLE IF EXISTS wallets`,

		`DROP TABLE IF EXISTS token_prices`,

		`DROP TABLE IF EXISTS block_headers`,
	}
}

func (obj *pgxcockroachDB) wrapTx(tx tagsql.Tx) txMethods {
	return &pgxcockroachTx{
		dialectTx: dialectTx{tx: tx},
		pgxcockroachImpl: &pgxcockroachImpl{
			db:     obj.db,
			driver: tx,
			txn:    true,
		},
	}
}

type pgxcockroachTx struct {
	dialectTx
	*pgxcockroachImpl
}

func pgxcockroachLogStmt(stmt string, args ...any) {
	// TODO: render placeholders
	if Logger != nil {
		out := fmt.Sprintf("stmt: %s\nargs: %v\n", stmt, pretty(args))
		Logger(out)
	}
}

type pretty []any

func (p pretty) Format(f fmt.State, c rune) {
	_, _ = fmt.Fprint(f, "[")
nextval:
	for i, val := range p {
		if i > 0 {
			_, _ = fmt.Fprint(f, ", ")
		}
		rv := reflect.ValueOf(val)
		if rv.Kind() == reflect.Ptr {
			if rv.IsNil() {
				_, _ = fmt.Fprint(f, "NULL")
				continue
			}
			val = rv.Elem().Interface()
		}
		switch v := val.(type) {
		case string:
			_, _ = fmt.Fprintf(f, "%q", v)
		case time.Time:
			_, _ = fmt.Fprintf(f, "%s", v.Format(time.RFC3339Nano))
		case []byte:
			for _, b := range v {
				if !unicode.IsPrint(rune(b)) {
					_, _ = fmt.Fprintf(f, "%#x", v)
					continue nextval
				}
			}
			_, _ = fmt.Fprintf(f, "%q", v)
		default:
			_, _ = fmt.Fprintf(f, "%v", v)
		}
	}
	_, _ = fmt.Fprint(f, "]")
}

type BlockHeader struct {
	ChainId   int64
	Hash      []byte
	Number    int64
	Timestamp time.Time
	CreatedAt time.Time
}

func (BlockHeader) _Table() string { return "block_headers" }

type BlockHeader_Update_Fields struct {
}

type BlockHeader_ChainId_Field struct {
	_set   bool
	_null  bool
	_value int64
}

func BlockHeader_ChainId(v int64) BlockHeader_ChainId_Field {
	return BlockHeader_ChainId_Field{_set: true, _value: v}
}

func (f BlockHeader_ChainId_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type BlockHeader_Hash_Field struct {
	_set   bool
	_null  bool
	_value []byte
}

func BlockHeader_Hash(v []byte) BlockHeader_Hash_Field {
	return BlockHeader_Hash_Field{_set: true, _value: v}
}

func (f BlockHeader_Hash_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type BlockHeader_Number_Field struct {
	_set   bool
	_null  bool
	_value int64
}

func BlockHeader_Number(v int64) BlockHeader_Number_Field {
	return BlockHeader_Number_Field{_set: true, _value: v}
}

func (f BlockHeader_Number_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type BlockHeader_Timestamp_Field struct {
	_set   bool
	_null  bool
	_value time.Time
}

func BlockHeader_Timestamp(v time.Time) BlockHeader_Timestamp_Field {
	return BlockHeader_Timestamp_Field{_set: true, _value: v}
}

func (f BlockHeader_Timestamp_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type BlockHeader_CreatedAt_Field struct {
	_set   bool
	_null  bool
	_value time.Time
}

func BlockHeader_CreatedAt(v time.Time) BlockHeader_CreatedAt_Field {
	return BlockHeader_CreatedAt_Field{_set: true, _value: v}
}

func (f BlockHeader_CreatedAt_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type TokenPrice struct {
	IntervalStart time.Time
	Price         int64
}

func (TokenPrice) _Table() string { return "token_prices" }

type TokenPrice_Update_Fields struct {
	Price TokenPrice_Price_Field
}

type TokenPrice_IntervalStart_Field struct {
	_set   bool
	_null  bool
	_value time.Time
}

func TokenPrice_IntervalStart(v time.Time) TokenPrice_IntervalStart_Field {
	return TokenPrice_IntervalStart_Field{_set: true, _value: v}
}

func (f TokenPrice_IntervalStart_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type TokenPrice_Price_Field struct {
	_set   bool
	_null  bool
	_value int64
}

func TokenPrice_Price(v int64) TokenPrice_Price_Field {
	return TokenPrice_Price_Field{_set: true, _value: v}
}

func (f TokenPrice_Price_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Wallet struct {
	Id        int64
	Address   []byte
	Claimed   *time.Time
	Satellite string
	Info      *string
	CreatedAt time.Time
}

func (Wallet) _Table() string { return "wallets" }

type Wallet_Create_Fields struct {
	Claimed Wallet_Claimed_Field
	Info    Wallet_Info_Field
}

type Wallet_Update_Fields struct {
	Claimed Wallet_Claimed_Field
	Info    Wallet_Info_Field
}

type Wallet_Id_Field struct {
	_set   bool
	_null  bool
	_value int64
}

func Wallet_Id(v int64) Wallet_Id_Field {
	return Wallet_Id_Field{_set: true, _value: v}
}

func (f Wallet_Id_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Wallet_Address_Field struct {
	_set   bool
	_null  bool
	_value []byte
}

func Wallet_Address(v []byte) Wallet_Address_Field {
	return Wallet_Address_Field{_set: true, _value: v}
}

func (f Wallet_Address_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Wallet_Claimed_Field struct {
	_set   bool
	_null  bool
	_value *time.Time
}

func Wallet_Claimed(v time.Time) Wallet_Claimed_Field {
	return Wallet_Claimed_Field{_set: true, _value: &v}
}

func Wallet_Claimed_Raw(v *time.Time) Wallet_Claimed_Field {
	if v == nil {
		return Wallet_Claimed_Null()
	}
	return Wallet_Claimed(*v)
}

func Wallet_Claimed_Null() Wallet_Claimed_Field {
	return Wallet_Claimed_Field{_set: true, _null: true}
}

func (f Wallet_Claimed_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Wallet_Claimed_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Wallet_Satellite_Field struct {
	_set   bool
	_null  bool
	_value string
}

func Wallet_Satellite(v string) Wallet_Satellite_Field {
	return Wallet_Satellite_Field{_set: true, _value: v}
}

func (f Wallet_Satellite_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Wallet_Info_Field struct {
	_set   bool
	_null  bool
	_value *string
}

func Wallet_Info(v string) Wallet_Info_Field {
	return Wallet_Info_Field{_set: true, _value: &v}
}

func Wallet_Info_Raw(v *string) Wallet_Info_Field {
	if v == nil {
		return Wallet_Info_Null()
	}
	return Wallet_Info(*v)
}

func Wallet_Info_Null() Wallet_Info_Field {
	return Wallet_Info_Field{_set: true, _null: true}
}

func (f Wallet_Info_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Wallet_Info_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Wallet_CreatedAt_Field struct {
	_set   bool
	_null  bool
	_value time.Time
}

func Wallet_CreatedAt(v time.Time) Wallet_CreatedAt_Field {
	return Wallet_CreatedAt_Field{_set: true, _value: v}
}

func (f Wallet_CreatedAt_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

func toUTC(t time.Time) time.Time {
	return t.UTC()
}

func toDate(t time.Time) time.Time {
	// keep up the minute portion so that translations between timezones will
	// continue to reflect properly.
	return t.Truncate(time.Minute)
}

//
// runtime support for building sql statements
//

type __sqlbundle_SQL interface {
	Render() string

	private()
}

type __sqlbundle_Dialect interface {
	// Rebind gives the opportunity to rewrite provided SQL into a SQL dialect.
	Rebind(sql string) string
}

type __sqlbundle_RenderOp int

const (
	__sqlbundle_NoFlatten __sqlbundle_RenderOp = iota
	__sqlbundle_NoTerminate
)

func __sqlbundle_RenderAll(dialect __sqlbundle_Dialect, sqls []__sqlbundle_SQL, ops ...__sqlbundle_RenderOp) []string {
	var rs []string
	for _, sql := range sqls {
		rs = append(rs, __sqlbundle_Render(dialect, sql, ops...))
	}
	return rs
}

func __sqlbundle_Render(dialect __sqlbundle_Dialect, sql __sqlbundle_SQL, ops ...__sqlbundle_RenderOp) string {
	out := sql.Render()

	flatten := true
	terminate := true
	for _, op := range ops {
		switch op {
		case __sqlbundle_NoFlatten:
			flatten = false
		case __sqlbundle_NoTerminate:
			terminate = false
		}
	}

	if flatten {
		out = __sqlbundle_flattenSQL(out)
	}
	if terminate {
		out += ";"
	}

	return dialect.Rebind(out)
}

func __sqlbundle_flattenSQL(x string) string {
	// trim whitespace from beginning and end
	s, e := 0, len(x)-1
	for s < len(x) && (x[s] == ' ' || x[s] == '\t' || x[s] == '\n') {
		s++
	}
	for s <= e && (x[e] == ' ' || x[e] == '\t' || x[e] == '\n') {
		e--
	}
	if s > e {
		return ""
	}
	x = x[s : e+1]

	// check for whitespace that needs fixing
	wasSpace := false
	for i := 0; i < len(x); i++ {
		r := x[i]
		justSpace := r == ' '
		if (wasSpace && justSpace) || r == '\t' || r == '\n' {
			// whitespace detected, start writing a new string
			var result strings.Builder
			result.Grow(len(x))
			if wasSpace {
				result.WriteString(x[:i-1])
			} else {
				result.WriteString(x[:i])
			}
			for p := i; p < len(x); p++ {
				for p < len(x) && (x[p] == ' ' || x[p] == '\t' || x[p] == '\n') {
					p++
				}
				result.WriteByte(' ')

				start := p
				for p < len(x) && !(x[p] == ' ' || x[p] == '\t' || x[p] == '\n') {
					p++
				}
				result.WriteString(x[start:p])
			}

			return result.String()
		}
		wasSpace = justSpace
	}

	// no problematic whitespace found
	return x
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_cockroach struct{}

func (p __sqlbundle_cockroach) Rebind(sql string) string {
	return __sqlbundle_postgres{}.Rebind(sql)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_pgx struct{}

func (p __sqlbundle_pgx) Rebind(sql string) string {
	return __sqlbundle_postgres{}.Rebind(sql)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_pgxcockroach struct{}

func (p __sqlbundle_pgxcockroach) Rebind(sql string) string {
	return __sqlbundle_postgres{}.Rebind(sql)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_postgres struct{}

func (p __sqlbundle_postgres) Rebind(sql string) string {
	type sqlParseState int
	const (
		sqlParseStart sqlParseState = iota
		sqlParseInStringLiteral
		sqlParseInQuotedIdentifier
		sqlParseInComment
	)

	out := make([]byte, 0, len(sql)+10)

	j := 1
	state := sqlParseStart
	for i := 0; i < len(sql); i++ {
		ch := sql[i]
		switch state {
		case sqlParseStart:
			switch ch {
			case '?':
				out = append(out, '$')
				out = append(out, strconv.Itoa(j)...)
				state = sqlParseStart
				j++
				continue
			case '-':
				if i+1 < len(sql) && sql[i+1] == '-' {
					state = sqlParseInComment
				}
			case '"':
				state = sqlParseInQuotedIdentifier
			case '\'':
				state = sqlParseInStringLiteral
			}
		case sqlParseInStringLiteral:
			if ch == '\'' {
				state = sqlParseStart
			}
		case sqlParseInQuotedIdentifier:
			if ch == '"' {
				state = sqlParseStart
			}
		case sqlParseInComment:
			if ch == '\n' {
				state = sqlParseStart
			}
		}
		out = append(out, ch)
	}

	return string(out)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_spanner struct{}

func (p __sqlbundle_spanner) Rebind(sql string) string {
	return sql
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_sqlite3 struct{}

func (s __sqlbundle_sqlite3) Rebind(sql string) string {
	return sql
}

type __sqlbundle_Literal string

func (__sqlbundle_Literal) private() {}

func (l __sqlbundle_Literal) Render() string { return string(l) }

type __sqlbundle_Literals struct {
	Join string
	SQLs []__sqlbundle_SQL
}

func (__sqlbundle_Literals) private() {}

func (l __sqlbundle_Literals) Render() string {
	var out bytes.Buffer

	first := true
	for _, sql := range l.SQLs {
		if sql == nil {
			continue
		}
		if !first {
			out.WriteString(l.Join)
		}
		first = false
		out.WriteString(sql.Render())
	}

	return out.String()
}

type __sqlbundle_Condition struct {
	// set at compile/embed time
	Name  string
	Left  string
	Equal bool
	Right string

	// set at runtime
	Null bool
}

func (*__sqlbundle_Condition) private() {}

func (c *__sqlbundle_Condition) Render() string {
	// TODO(jeff): maybe check if we can use placeholders instead of the
	// literal null: this would make the templates easier.

	switch {
	case c.Equal && c.Null:
		return c.Left + " is null"
	case c.Equal && !c.Null:
		return c.Left + " = " + c.Right
	case !c.Equal && c.Null:
		return c.Left + " is not null"
	case !c.Equal && !c.Null:
		return c.Left + " != " + c.Right
	default:
		panic("unhandled case")
	}
}

type __sqlbundle_Hole struct {
	// set at compiile/embed time
	Name string

	// set at runtime or possibly embed time
	SQL __sqlbundle_SQL
}

func (*__sqlbundle_Hole) private() {}

func (h *__sqlbundle_Hole) Render() string {
	if h.SQL == nil {
		return ""
	}
	return h.SQL.Render()
}

//
// end runtime support for building sql statements
//

func (obj *pgxImpl) Create_BlockHeader(ctx context.Context,
	block_header_chain_id BlockHeader_ChainId_Field,
	block_header_hash BlockHeader_Hash_Field,
	block_header_number BlockHeader_Number_Field,
	block_header_timestamp BlockHeader_Timestamp_Field) (
	block_header *BlockHeader, err error) {
	__chain_id_val := block_header_chain_id.value()
	__hash_val := block_header_hash.value()
	__number_val := block_header_number.value()
	__timestamp_val := block_header_timestamp.value()

	var __columns = &__sqlbundle_Hole{SQL: __sqlbundle_Literal("chain_id, hash, number, timestamp")}
	var __placeholders = &__sqlbundle_Hole{SQL: __sqlbundle_Literal("?, ?, ?, ?")}
	var __clause = &__sqlbundle_Hole{SQL: __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("("), __columns, __sqlbundle_Literal(") VALUES ("), __placeholders, __sqlbundle_Literal(")")}}}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("INSERT INTO block_headers "), __clause, __sqlbundle_Literal(" RETURNING block_headers.chain_id, block_headers.hash, block_headers.number, block_headers.timestamp, block_headers.created_at")}}

	var __values []any
	__values = append(__values, __chain_id_val, __hash_val, __number_val, __timestamp_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	block_header = &BlockHeader{}
	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&block_header.ChainId, &block_header.Hash, &block_header.Number, &block_header.Timestamp, &block_header.CreatedAt)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return block_header, nil

}

func (obj *pgxImpl) ReplaceNoReturn_TokenPrice(ctx context.Context,
	token_price_interval_start TokenPrice_IntervalStart_Field,
	token_price_price TokenPrice_Price_Field) (
	err error) {
	__interval_start_val := token_price_interval_start.value()
	__price_val := token_price_price.value()

	var __embed_stmt = __sqlbundle_Literal("INSERT INTO token_prices ( interval_start, price ) VALUES ( ?, ? ) ON CONFLICT ( interval_start ) DO UPDATE SET interval_start = EXCLUDED.interval_start, price = EXCLUDED.price")

	var __values []any
	__values = append(__values, __interval_start_val, __price_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	_, err = obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return obj.makeErr(err)
	}
	return nil

}

func (obj *pgxImpl) Create_Wallet(ctx context.Context,
	wallet_address Wallet_Address_Field,
	wallet_satellite Wallet_Satellite_Field,
	optional Wallet_Create_Fields) (
	wallet *Wallet, err error) {
	__address_val := wallet_address.value()
	__claimed_val := optional.Claimed.value()
	__satellite_val := wallet_satellite.value()
	__info_val := optional.Info.value()

	var __columns = &__sqlbundle_Hole{SQL: __sqlbundle_Literal("address, claimed, satellite, info")}
	var __placeholders = &__sqlbundle_Hole{SQL: __sqlbundle_Literal("?, ?, ?, ?")}
	var __clause = &__sqlbundle_Hole{SQL: __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("("), __columns, __sqlbundle_Literal(") VALUES ("), __placeholders, __sqlbundle_Literal(")")}}}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("INSERT INTO wallets "), __clause, __sqlbundle_Literal(" RETURNING wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at")}}

	var __values []any
	__values = append(__values, __address_val, __claimed_val, __satellite_val, __info_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	wallet = &Wallet{}
	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return wallet, nil

}

func (obj *pgxImpl) All_BlockHeader_OrderBy_Desc_Timestamp(ctx context.Context) (
	rows []*BlockHeader, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT block_headers.chain_id, block_headers.hash, block_headers.number, block_headers.timestamp, block_headers.created_at FROM block_headers ORDER BY block_headers.timestamp DESC")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		rows, err = func() (rows []*BlockHeader, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			for __rows.Next() {
				block_header := &BlockHeader{}
				err = __rows.Scan(&block_header.ChainId, &block_header.Hash, &block_header.Number, &block_header.Timestamp, &block_header.CreatedAt)
				if err != nil {
					return nil, err
				}
				rows = append(rows, block_header)
			}
			return rows, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return rows, nil
	}

}

func (obj *pgxImpl) Get_BlockHeader_By_ChainId_And_Hash(ctx context.Context,
	block_header_chain_id BlockHeader_ChainId_Field,
	block_header_hash BlockHeader_Hash_Field) (
	block_header *BlockHeader, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT block_headers.chain_id, block_headers.hash, block_headers.number, block_headers.timestamp, block_headers.created_at FROM block_headers WHERE block_headers.chain_id = ? AND block_headers.hash = ?")

	var __values []any
	__values = append(__values, block_header_chain_id.value(), block_header_hash.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	block_header = &BlockHeader{}
	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&block_header.ChainId, &block_header.Hash, &block_header.Number, &block_header.Timestamp, &block_header.CreatedAt)
	if err != nil {
		return (*BlockHeader)(nil), obj.makeErr(err)
	}
	return block_header, nil

}

func (obj *pgxImpl) Get_BlockHeader_By_ChainId_And_Number(ctx context.Context,
	block_header_chain_id BlockHeader_ChainId_Field,
	block_header_number BlockHeader_Number_Field) (
	block_header *BlockHeader, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT block_headers.chain_id, block_headers.hash, block_headers.number, block_headers.timestamp, block_headers.created_at FROM block_headers WHERE block_headers.chain_id = ? AND block_headers.number = ? LIMIT 2")

	var __values []any
	__values = append(__values, block_header_chain_id.value(), block_header_number.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		block_header, err = func() (block_header *BlockHeader, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			if !__rows.Next() {
				return nil, sql.ErrNoRows
			}

			block_header = &BlockHeader{}
			err = __rows.Scan(&block_header.ChainId, &block_header.Hash, &block_header.Number, &block_header.Timestamp, &block_header.CreatedAt)
			if err != nil {
				return nil, err
			}

			if __rows.Next() {
				return nil, errTooManyRows
			}

			return block_header, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			if errors.Is(err, errTooManyRows) {
				return nil, tooManyRows("BlockHeader_By_ChainId_And_Number")
			}
			return nil, obj.makeErr(err)
		}
		return block_header, nil
	}

}

func (obj *pgxImpl) Get_TokenPrice_By_IntervalStart(ctx context.Context,
	token_price_interval_start TokenPrice_IntervalStart_Field) (
	token_price *TokenPrice, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT token_prices.interval_start, token_prices.price FROM token_prices WHERE token_prices.interval_start = ?")

	var __values []any
	__values = append(__values, token_price_interval_start.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	token_price = &TokenPrice{}
	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&token_price.IntervalStart, &token_price.Price)
	if err != nil {
		return (*TokenPrice)(nil), obj.makeErr(err)
	}
	return token_price, nil

}

func (obj *pgxImpl) First_TokenPrice_By_IntervalStart_Less_OrderBy_Desc_IntervalStart(ctx context.Context,
	token_price_interval_start_less TokenPrice_IntervalStart_Field) (
	token_price *TokenPrice, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT token_prices.interval_start, token_prices.price FROM token_prices WHERE token_prices.interval_start < ? ORDER BY token_prices.interval_start DESC LIMIT 1 OFFSET 0")

	var __values []any
	__values = append(__values, token_price_interval_start_less.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		token_price, err = func() (token_price *TokenPrice, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			if !__rows.Next() {
				return nil, nil
			}

			token_price = &TokenPrice{}
			err = __rows.Scan(&token_price.IntervalStart, &token_price.Price)
			if err != nil {
				return nil, err
			}

			return token_price, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return token_price, nil
	}

}

func (obj *pgxImpl) Get_Wallet_By_Address_And_Satellite(ctx context.Context,
	wallet_address Wallet_Address_Field,
	wallet_satellite Wallet_Satellite_Field) (
	wallet *Wallet, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at FROM wallets WHERE wallets.address = ? AND wallets.satellite = ? LIMIT 2")

	var __values []any
	__values = append(__values, wallet_address.value(), wallet_satellite.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		wallet, err = func() (wallet *Wallet, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			if !__rows.Next() {
				return nil, sql.ErrNoRows
			}

			wallet = &Wallet{}
			err = __rows.Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
			if err != nil {
				return nil, err
			}

			if __rows.Next() {
				return nil, errTooManyRows
			}

			return wallet, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			if errors.Is(err, errTooManyRows) {
				return nil, tooManyRows("Wallet_By_Address_And_Satellite")
			}
			return nil, obj.makeErr(err)
		}
		return wallet, nil
	}

}

func (obj *pgxImpl) First_Wallet_By_Claimed_Is_Null_And_Satellite(ctx context.Context,
	wallet_satellite Wallet_Satellite_Field) (
	wallet *Wallet, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at FROM wallets WHERE wallets.claimed is NULL AND wallets.satellite = ? LIMIT 1 OFFSET 0")

	var __values []any
	__values = append(__values, wallet_satellite.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		wallet, err = func() (wallet *Wallet, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			if !__rows.Next() {
				return nil, nil
			}

			wallet = &Wallet{}
			err = __rows.Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
			if err != nil {
				return nil, err
			}

			return wallet, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return wallet, nil
	}

}

func (obj *pgxImpl) Count_Wallet_Address(ctx context.Context) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT COUNT(*) FROM wallets")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&count)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (obj *pgxImpl) Count_Wallet_By_Claimed_IsNot_Null(ctx context.Context) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT COUNT(*) FROM wallets WHERE wallets.claimed is not NULL")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&count)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (obj *pgxImpl) Count_Wallet_By_Claimed_Is_Null(ctx context.Context) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT COUNT(*) FROM wallets WHERE wallets.claimed is NULL")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&count)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (obj *pgxImpl) All_Wallet_By_Claimed_IsNot_Null(ctx context.Context) (
	rows []*Wallet, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at FROM wallets WHERE wallets.claimed is not NULL")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		rows, err = func() (rows []*Wallet, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			for __rows.Next() {
				wallet := &Wallet{}
				err = __rows.Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
				if err != nil {
					return nil, err
				}
				rows = append(rows, wallet)
			}
			return rows, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return rows, nil
	}

}

func (obj *pgxImpl) All_Wallet_By_Satellite_And_Claimed_IsNot_Null(ctx context.Context,
	wallet_satellite Wallet_Satellite_Field) (
	rows []*Wallet, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at FROM wallets WHERE wallets.satellite = ? AND wallets.claimed is not NULL")

	var __values []any
	__values = append(__values, wallet_satellite.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		rows, err = func() (rows []*Wallet, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			for __rows.Next() {
				wallet := &Wallet{}
				err = __rows.Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
				if err != nil {
					return nil, err
				}
				rows = append(rows, wallet)
			}
			return rows, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return rows, nil
	}

}

func (obj *pgxImpl) Update_Wallet_By_Id(ctx context.Context,
	wallet_id Wallet_Id_Field,
	update Wallet_Update_Fields) (
	wallet *Wallet, err error) {

	var __sets = &__sqlbundle_Hole{}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("UPDATE wallets SET "), __sets, __sqlbundle_Literal(" WHERE wallets.id = ? RETURNING wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at")}}

	__sets_sql := __sqlbundle_Literals{Join: ", "}
	var __values []any
	var __args []any

	if update.Claimed._set {
		__values = append(__values, update.Claimed.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("claimed = ?"))
	}

	if update.Info._set {
		__values = append(__values, update.Info.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("info = ?"))
	}

	if len(__sets_sql.SQLs) == 0 {
		return nil, emptyUpdate()
	}

	__args = append(__args, wallet_id.value())

	__values = append(__values, __args...)
	__sets.SQL = __sets_sql

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	wallet = &Wallet{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return wallet, nil
}

func (obj *pgxImpl) Delete_BlockHeader_By_ChainId_And_Hash(ctx context.Context,
	block_header_chain_id BlockHeader_ChainId_Field,
	block_header_hash BlockHeader_Hash_Field) (
	deleted bool, err error) {

	var __embed_stmt = __sqlbundle_Literal("DELETE FROM block_headers WHERE block_headers.chain_id = ? AND block_headers.hash = ?")

	var __values []any
	__values = append(__values, block_header_chain_id.value(), block_header_hash.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return false, obj.makeErr(err)
	}

	__count, err := __res.RowsAffected()
	if err != nil {
		return false, obj.makeErr(err)
	}

	return __count > 0, nil

}

func (obj *pgxImpl) Delete_BlockHeader_By_Timestamp_Less(ctx context.Context,
	block_header_timestamp_less BlockHeader_Timestamp_Field) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("DELETE FROM block_headers WHERE block_headers.timestamp < ?")

	var __values []any
	__values = append(__values, block_header_timestamp_less.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (obj *pgxImpl) Delete_TokenPrice_By_IntervalStart_Less(ctx context.Context,
	token_price_interval_start_less TokenPrice_IntervalStart_Field) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("DELETE FROM token_prices WHERE token_prices.interval_start < ?")

	var __values []any
	__values = append(__values, token_price_interval_start_less.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (impl pgxImpl) isConstraintError(err error) (constraint string, ok bool) {
	if e, ok := err.(*pgconn.PgError); ok {
		if e.Code[:2] == "23" {
			return e.ConstraintName, true
		}
	}
	return "", false
}

func (obj *pgxImpl) deleteAll(ctx context.Context) (count int64, err error) {
	var __res sql.Result
	var __count int64
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM wallets;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM token_prices;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM block_headers;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count

	return count, nil

}

func (obj *pgxcockroachImpl) Create_BlockHeader(ctx context.Context,
	block_header_chain_id BlockHeader_ChainId_Field,
	block_header_hash BlockHeader_Hash_Field,
	block_header_number BlockHeader_Number_Field,
	block_header_timestamp BlockHeader_Timestamp_Field) (
	block_header *BlockHeader, err error) {
	__chain_id_val := block_header_chain_id.value()
	__hash_val := block_header_hash.value()
	__number_val := block_header_number.value()
	__timestamp_val := block_header_timestamp.value()

	var __columns = &__sqlbundle_Hole{SQL: __sqlbundle_Literal("chain_id, hash, number, timestamp")}
	var __placeholders = &__sqlbundle_Hole{SQL: __sqlbundle_Literal("?, ?, ?, ?")}
	var __clause = &__sqlbundle_Hole{SQL: __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("("), __columns, __sqlbundle_Literal(") VALUES ("), __placeholders, __sqlbundle_Literal(")")}}}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("INSERT INTO block_headers "), __clause, __sqlbundle_Literal(" RETURNING block_headers.chain_id, block_headers.hash, block_headers.number, block_headers.timestamp, block_headers.created_at")}}

	var __values []any
	__values = append(__values, __chain_id_val, __hash_val, __number_val, __timestamp_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	block_header = &BlockHeader{}
	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&block_header.ChainId, &block_header.Hash, &block_header.Number, &block_header.Timestamp, &block_header.CreatedAt)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return block_header, nil

}

func (obj *pgxcockroachImpl) ReplaceNoReturn_TokenPrice(ctx context.Context,
	token_price_interval_start TokenPrice_IntervalStart_Field,
	token_price_price TokenPrice_Price_Field) (
	err error) {
	__interval_start_val := token_price_interval_start.value()
	__price_val := token_price_price.value()

	var __embed_stmt = __sqlbundle_Literal("UPSERT INTO token_prices ( interval_start, price ) VALUES ( ?, ? )")

	var __values []any
	__values = append(__values, __interval_start_val, __price_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	_, err = obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return obj.makeErr(err)
	}
	return nil

}

func (obj *pgxcockroachImpl) Create_Wallet(ctx context.Context,
	wallet_address Wallet_Address_Field,
	wallet_satellite Wallet_Satellite_Field,
	optional Wallet_Create_Fields) (
	wallet *Wallet, err error) {
	__address_val := wallet_address.value()
	__claimed_val := optional.Claimed.value()
	__satellite_val := wallet_satellite.value()
	__info_val := optional.Info.value()

	var __columns = &__sqlbundle_Hole{SQL: __sqlbundle_Literal("address, claimed, satellite, info")}
	var __placeholders = &__sqlbundle_Hole{SQL: __sqlbundle_Literal("?, ?, ?, ?")}
	var __clause = &__sqlbundle_Hole{SQL: __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("("), __columns, __sqlbundle_Literal(") VALUES ("), __placeholders, __sqlbundle_Literal(")")}}}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("INSERT INTO wallets "), __clause, __sqlbundle_Literal(" RETURNING wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at")}}

	var __values []any
	__values = append(__values, __address_val, __claimed_val, __satellite_val, __info_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	wallet = &Wallet{}
	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return wallet, nil

}

func (obj *pgxcockroachImpl) All_BlockHeader_OrderBy_Desc_Timestamp(ctx context.Context) (
	rows []*BlockHeader, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT block_headers.chain_id, block_headers.hash, block_headers.number, block_headers.timestamp, block_headers.created_at FROM block_headers ORDER BY block_headers.timestamp DESC")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		rows, err = func() (rows []*BlockHeader, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			for __rows.Next() {
				block_header := &BlockHeader{}
				err = __rows.Scan(&block_header.ChainId, &block_header.Hash, &block_header.Number, &block_header.Timestamp, &block_header.CreatedAt)
				if err != nil {
					return nil, err
				}
				rows = append(rows, block_header)
			}
			return rows, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return rows, nil
	}

}

func (obj *pgxcockroachImpl) Get_BlockHeader_By_ChainId_And_Hash(ctx context.Context,
	block_header_chain_id BlockHeader_ChainId_Field,
	block_header_hash BlockHeader_Hash_Field) (
	block_header *BlockHeader, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT block_headers.chain_id, block_headers.hash, block_headers.number, block_headers.timestamp, block_headers.created_at FROM block_headers WHERE block_headers.chain_id = ? AND block_headers.hash = ?")

	var __values []any
	__values = append(__values, block_header_chain_id.value(), block_header_hash.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	block_header = &BlockHeader{}
	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&block_header.ChainId, &block_header.Hash, &block_header.Number, &block_header.Timestamp, &block_header.CreatedAt)
	if err != nil {
		return (*BlockHeader)(nil), obj.makeErr(err)
	}
	return block_header, nil

}

func (obj *pgxcockroachImpl) Get_BlockHeader_By_ChainId_And_Number(ctx context.Context,
	block_header_chain_id BlockHeader_ChainId_Field,
	block_header_number BlockHeader_Number_Field) (
	block_header *BlockHeader, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT block_headers.chain_id, block_headers.hash, block_headers.number, block_headers.timestamp, block_headers.created_at FROM block_headers WHERE block_headers.chain_id = ? AND block_headers.number = ? LIMIT 2")

	var __values []any
	__values = append(__values, block_header_chain_id.value(), block_header_number.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		block_header, err = func() (block_header *BlockHeader, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			if !__rows.Next() {
				return nil, sql.ErrNoRows
			}

			block_header = &BlockHeader{}
			err = __rows.Scan(&block_header.ChainId, &block_header.Hash, &block_header.Number, &block_header.Timestamp, &block_header.CreatedAt)
			if err != nil {
				return nil, err
			}

			if __rows.Next() {
				return nil, errTooManyRows
			}

			return block_header, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			if errors.Is(err, errTooManyRows) {
				return nil, tooManyRows("BlockHeader_By_ChainId_And_Number")
			}
			return nil, obj.makeErr(err)
		}
		return block_header, nil
	}

}

func (obj *pgxcockroachImpl) Get_TokenPrice_By_IntervalStart(ctx context.Context,
	token_price_interval_start TokenPrice_IntervalStart_Field) (
	token_price *TokenPrice, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT token_prices.interval_start, token_prices.price FROM token_prices WHERE token_prices.interval_start = ?")

	var __values []any
	__values = append(__values, token_price_interval_start.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	token_price = &TokenPrice{}
	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&token_price.IntervalStart, &token_price.Price)
	if err != nil {
		return (*TokenPrice)(nil), obj.makeErr(err)
	}
	return token_price, nil

}

func (obj *pgxcockroachImpl) First_TokenPrice_By_IntervalStart_Less_OrderBy_Desc_IntervalStart(ctx context.Context,
	token_price_interval_start_less TokenPrice_IntervalStart_Field) (
	token_price *TokenPrice, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT token_prices.interval_start, token_prices.price FROM token_prices WHERE token_prices.interval_start < ? ORDER BY token_prices.interval_start DESC LIMIT 1 OFFSET 0")

	var __values []any
	__values = append(__values, token_price_interval_start_less.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		token_price, err = func() (token_price *TokenPrice, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			if !__rows.Next() {
				return nil, nil
			}

			token_price = &TokenPrice{}
			err = __rows.Scan(&token_price.IntervalStart, &token_price.Price)
			if err != nil {
				return nil, err
			}

			return token_price, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return token_price, nil
	}

}

func (obj *pgxcockroachImpl) Get_Wallet_By_Address_And_Satellite(ctx context.Context,
	wallet_address Wallet_Address_Field,
	wallet_satellite Wallet_Satellite_Field) (
	wallet *Wallet, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at FROM wallets WHERE wallets.address = ? AND wallets.satellite = ? LIMIT 2")

	var __values []any
	__values = append(__values, wallet_address.value(), wallet_satellite.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		wallet, err = func() (wallet *Wallet, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			if !__rows.Next() {
				return nil, sql.ErrNoRows
			}

			wallet = &Wallet{}
			err = __rows.Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
			if err != nil {
				return nil, err
			}

			if __rows.Next() {
				return nil, errTooManyRows
			}

			return wallet, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			if errors.Is(err, errTooManyRows) {
				return nil, tooManyRows("Wallet_By_Address_And_Satellite")
			}
			return nil, obj.makeErr(err)
		}
		return wallet, nil
	}

}

func (obj *pgxcockroachImpl) First_Wallet_By_Claimed_Is_Null_And_Satellite(ctx context.Context,
	wallet_satellite Wallet_Satellite_Field) (
	wallet *Wallet, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at FROM wallets WHERE wallets.claimed is NULL AND wallets.satellite = ? LIMIT 1 OFFSET 0")

	var __values []any
	__values = append(__values, wallet_satellite.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		wallet, err = func() (wallet *Wallet, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			if !__rows.Next() {
				return nil, nil
			}

			wallet = &Wallet{}
			err = __rows.Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
			if err != nil {
				return nil, err
			}

			return wallet, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return wallet, nil
	}

}

func (obj *pgxcockroachImpl) Count_Wallet_Address(ctx context.Context) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT COUNT(*) FROM wallets")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&count)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (obj *pgxcockroachImpl) Count_Wallet_By_Claimed_IsNot_Null(ctx context.Context) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT COUNT(*) FROM wallets WHERE wallets.claimed is not NULL")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&count)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (obj *pgxcockroachImpl) Count_Wallet_By_Claimed_Is_Null(ctx context.Context) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT COUNT(*) FROM wallets WHERE wallets.claimed is NULL")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&count)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (obj *pgxcockroachImpl) All_Wallet_By_Claimed_IsNot_Null(ctx context.Context) (
	rows []*Wallet, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at FROM wallets WHERE wallets.claimed is not NULL")

	var __values []any

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		rows, err = func() (rows []*Wallet, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			for __rows.Next() {
				wallet := &Wallet{}
				err = __rows.Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
				if err != nil {
					return nil, err
				}
				rows = append(rows, wallet)
			}
			return rows, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return rows, nil
	}

}

func (obj *pgxcockroachImpl) All_Wallet_By_Satellite_And_Claimed_IsNot_Null(ctx context.Context,
	wallet_satellite Wallet_Satellite_Field) (
	rows []*Wallet, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at FROM wallets WHERE wallets.satellite = ? AND wallets.claimed is not NULL")

	var __values []any
	__values = append(__values, wallet_satellite.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	for {
		rows, err = func() (rows []*Wallet, err error) {
			__rows, err := obj.driver.QueryContext(ctx, __stmt, __values...)
			if err != nil {
				return nil, err
			}
			defer closeRows(__rows, &err)

			for __rows.Next() {
				wallet := &Wallet{}
				err = __rows.Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
				if err != nil {
					return nil, err
				}
				rows = append(rows, wallet)
			}
			return rows, nil
		}()
		if err != nil {
			if obj.shouldRetry(err) {
				continue
			}
			return nil, obj.makeErr(err)
		}
		return rows, nil
	}

}

func (obj *pgxcockroachImpl) Update_Wallet_By_Id(ctx context.Context,
	wallet_id Wallet_Id_Field,
	update Wallet_Update_Fields) (
	wallet *Wallet, err error) {

	var __sets = &__sqlbundle_Hole{}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("UPDATE wallets SET "), __sets, __sqlbundle_Literal(" WHERE wallets.id = ? RETURNING wallets.id, wallets.address, wallets.claimed, wallets.satellite, wallets.info, wallets.created_at")}}

	__sets_sql := __sqlbundle_Literals{Join: ", "}
	var __values []any
	var __args []any

	if update.Claimed._set {
		__values = append(__values, update.Claimed.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("claimed = ?"))
	}

	if update.Info._set {
		__values = append(__values, update.Info.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("info = ?"))
	}

	if len(__sets_sql.SQLs) == 0 {
		return nil, emptyUpdate()
	}

	__args = append(__args, wallet_id.value())

	__values = append(__values, __args...)
	__sets.SQL = __sets_sql

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	wallet = &Wallet{}
	err = obj.driver.QueryRowContext(ctx, __stmt, __values...).Scan(&wallet.Id, &wallet.Address, &wallet.Claimed, &wallet.Satellite, &wallet.Info, &wallet.CreatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, obj.makeErr(err)
	}
	return wallet, nil
}

func (obj *pgxcockroachImpl) Delete_BlockHeader_By_ChainId_And_Hash(ctx context.Context,
	block_header_chain_id BlockHeader_ChainId_Field,
	block_header_hash BlockHeader_Hash_Field) (
	deleted bool, err error) {

	var __embed_stmt = __sqlbundle_Literal("DELETE FROM block_headers WHERE block_headers.chain_id = ? AND block_headers.hash = ?")

	var __values []any
	__values = append(__values, block_header_chain_id.value(), block_header_hash.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return false, obj.makeErr(err)
	}

	__count, err := __res.RowsAffected()
	if err != nil {
		return false, obj.makeErr(err)
	}

	return __count > 0, nil

}

func (obj *pgxcockroachImpl) Delete_BlockHeader_By_Timestamp_Less(ctx context.Context,
	block_header_timestamp_less BlockHeader_Timestamp_Field) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("DELETE FROM block_headers WHERE block_headers.timestamp < ?")

	var __values []any
	__values = append(__values, block_header_timestamp_less.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (obj *pgxcockroachImpl) Delete_TokenPrice_By_IntervalStart_Less(ctx context.Context,
	token_price_interval_start_less TokenPrice_IntervalStart_Field) (
	count int64, err error) {

	var __embed_stmt = __sqlbundle_Literal("DELETE FROM token_prices WHERE token_prices.interval_start < ?")

	var __values []any
	__values = append(__values, token_price_interval_start_less.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return 0, obj.makeErr(err)
	}

	count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}

	return count, nil

}

func (impl pgxcockroachImpl) isConstraintError(err error) (constraint string, ok bool) {
	if e, ok := err.(*pgconn.PgError); ok {
		if e.Code[:2] == "23" {
			return e.ConstraintName, true
		}
	}
	return "", false
}

func (obj *pgxcockroachImpl) deleteAll(ctx context.Context) (count int64, err error) {
	var __res sql.Result
	var __count int64
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM wallets;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM token_prices;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM block_headers;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count

	return count, nil

}

type Methods interface {
	All_BlockHeader_OrderBy_Desc_Timestamp(ctx context.Context) (
		rows []*BlockHeader, err error)

	All_Wallet_By_Claimed_IsNot_Null(ctx context.Context) (
		rows []*Wallet, err error)

	All_Wallet_By_Satellite_And_Claimed_IsNot_Null(ctx context.Context,
		wallet_satellite Wallet_Satellite_Field) (
		rows []*Wallet, err error)

	Count_Wallet_Address(ctx context.Context) (
		count int64, err error)

	Count_Wallet_By_Claimed_IsNot_Null(ctx context.Context) (
		count int64, err error)

	Count_Wallet_By_Claimed_Is_Null(ctx context.Context) (
		count int64, err error)

	Create_BlockHeader(ctx context.Context,
		block_header_chain_id BlockHeader_ChainId_Field,
		block_header_hash BlockHeader_Hash_Field,
		block_header_number BlockHeader_Number_Field,
		block_header_timestamp BlockHeader_Timestamp_Field) (
		block_header *BlockHeader, err error)

	Create_Wallet(ctx context.Context,
		wallet_address Wallet_Address_Field,
		wallet_satellite Wallet_Satellite_Field,
		optional Wallet_Create_Fields) (
		wallet *Wallet, err error)

	Delete_BlockHeader_By_ChainId_And_Hash(ctx context.Context,
		block_header_chain_id BlockHeader_ChainId_Field,
		block_header_hash BlockHeader_Hash_Field) (
		deleted bool, err error)

	Delete_BlockHeader_By_Timestamp_Less(ctx context.Context,
		block_header_timestamp_less BlockHeader_Timestamp_Field) (
		count int64, err error)

	Delete_TokenPrice_By_IntervalStart_Less(ctx context.Context,
		token_price_interval_start_less TokenPrice_IntervalStart_Field) (
		count int64, err error)

	First_TokenPrice_By_IntervalStart_Less_OrderBy_Desc_IntervalStart(ctx context.Context,
		token_price_interval_start_less TokenPrice_IntervalStart_Field) (
		token_price *TokenPrice, err error)

	First_Wallet_By_Claimed_Is_Null_And_Satellite(ctx context.Context,
		wallet_satellite Wallet_Satellite_Field) (
		wallet *Wallet, err error)

	Get_BlockHeader_By_ChainId_And_Hash(ctx context.Context,
		block_header_chain_id BlockHeader_ChainId_Field,
		block_header_hash BlockHeader_Hash_Field) (
		block_header *BlockHeader, err error)

	Get_BlockHeader_By_ChainId_And_Number(ctx context.Context,
		block_header_chain_id BlockHeader_ChainId_Field,
		block_header_number BlockHeader_Number_Field) (
		block_header *BlockHeader, err error)

	Get_TokenPrice_By_IntervalStart(ctx context.Context,
		token_price_interval_start TokenPrice_IntervalStart_Field) (
		token_price *TokenPrice, err error)

	Get_Wallet_By_Address_And_Satellite(ctx context.Context,
		wallet_address Wallet_Address_Field,
		wallet_satellite Wallet_Satellite_Field) (
		wallet *Wallet, err error)

	ReplaceNoReturn_TokenPrice(ctx context.Context,
		token_price_interval_start TokenPrice_IntervalStart_Field,
		token_price_price TokenPrice_Price_Field) (
		err error)

	Update_Wallet_By_Id(ctx context.Context,
		wallet_id Wallet_Id_Field,
		update Wallet_Update_Fields) (
		wallet *Wallet, err error)
}

type TxMethods interface {
	Methods

	Rebind(s string) string
	Commit() error
	Rollback() error
}

type txMethods interface {
	TxMethods

	deleteAll(ctx context.Context) (int64, error)
	makeErr(err error) error
}

type DBMethods interface {
	Methods

	Schema() []string
	DropSchema() []string

	Rebind(sql string) string
}

type dbMethods interface {
	DBMethods

	wrapTx(tx tagsql.Tx) txMethods
	makeErr(err error) error
}

func openpgx(source string) (*sql.DB, error) {
	return sql.Open("pgx", source)
}

func openpgxcockroach(source string) (*sql.DB, error) {
	// try first with "cockroach" as a driver in case someone has registered
	// some special stuff. if that fails, then try again with "pgx" as
	// the driver.
	db, err := sql.Open("cockroach", source)
	if err != nil {
		db, err = sql.Open("pgx", source)
	}
	return db, err
}
