-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE block_headers (
	hash bytea NOT NULL,
	number bigint NOT NULL,
	timestamp timestamp with time zone NOT NULL,
	created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( hash )
);
CREATE TABLE wallets (
	address bytea NOT NULL,
	claimed timestamp with time zone,
	created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( address )
);
CREATE INDEX block_header_timestamp ON block_headers ( timestamp ) ;
