#!/bin/bash
# Copyright (C) 2026 Storj Labs, Inc.
# See LICENSE for copying information.

# Compiles the sweeper contracts and writes their bytecode to bytecode.go.
# build/ is not committed (the repository ignores it), so bytecode.go is what
# lets the tests deploy these contracts without a Solidity toolchain. Re-run
# this after changing any .sol file.

set -euo pipefail
cd "$(dirname "$0")"

solc --bin --bin-runtime --abi --optimize --overwrite -o build/ \
    sweeper.sol testtoken.sol multicall3.sol

bin() { tr -d '\n' < "build/$1"; }

cat > bytecode.go <<EOF
// Copyright (C) 2026 Storj Labs, Inc.
// See LICENSE for copying information.

// Package contract holds the sweeper's Solidity sources and the bytecode
// compiled from them.
//
// Code generated by compile.sh. DO NOT EDIT.
package contract

// Sweeper7702Bin is the deployment bytecode of sweeper.sol, the contract the
// deposit wallets delegate their code to. Append the ABI-encoded destination
// address the contract sweeps into before deploying.
const Sweeper7702Bin = "$(bin Sweeper7702.bin)"

// TestTokenBin is the deployment bytecode of testtoken.sol, a minimal ERC20
// used by the tests. Append the ABI-encoded decimals before deploying.
const TestTokenBin = "$(bin TestToken.bin)"

// Multicall3Runtime is the runtime bytecode of multicall3.sol. Tests preload it
// at the canonical Multicall3 address, which a fresh chain has nothing at.
const Multicall3Runtime = "$(bin Multicall3.bin-runtime)"
EOF

gofmt -w bytecode.go
